[project]
name = "football-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pip>=24.3.1",
    "roboflow>=1.1.50",
    "supervision>=0.24.0",
    "ultralytics>=8.3.57",
]
